site_name: Canvas Shader Development
theme: readthedocs
nav:
  - index.md
  - Pipeline:
    - pipeline/what_is_pipeline.md
    - pipeline/making_a_pipeline.md
    - pipeline/fabulous_pipeline.md
    - Material Program: dummy.md
    - Pass Program: dummy.md
    - Pipeline options: dummy.md
    - Shadow map: pipeline/shadow_map.md
    - PBR: pipeline/pbr.md
    - Colored Lights (WIP): dummy.md
  - Materials:
    - Material shader: material/material_shader.md
    - Material: dummy.md
    - Material map: dummy.md
  - API Reference:
    - FREX Shader API: frex/index.md
